stages:
- code-analysis
- test
.unit-test: &unit-test
    script:
    - apk add make git build-base --no-cache
    - pip install -r requirements.txt
    - pytest -v --cov=. --cov-report=term --cov-report=html

unit test (integrated branch):
    stage: test
    tags: [python-361]
    coverage: '/TOTAL.+?(\d+)%/'
    <<: *unit-test

code convention:
    stage: code-analysis
    tags: [python-361]
    script:
    - apk add make git build-base --no-cache
    - pip install -r requirements.txt
    - flake8
    - pycodestyle
