services:
  db:
    image: postgres:14.1-alpine
    container_name: service-db
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgres/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  service:
    container_name: service-app
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    restart: no
    depends_on:
      - db

volumes:
  db_data:
